/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/contracts/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contract Sample
         * @description Expose the typed Phase 0 sample; no operational feature or live claim.
         */
        get: operations["contract_sample_api_v1_contracts_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assumption */
        Assumption: {
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Entered At
             * Format: date-time
             */
            entered_at: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Key */
            key: string;
            /** Owner */
            owner: string;
            /** Rationale */
            rationale: string;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Source Gap */
            source_gap: string;
            /** @default DRAFT */
            status: components["schemas"]["AssumptionStatus"];
            /** Supersedes Id */
            supersedes_id?: string | null;
            /** @default ASSUMPTION */
            truth_class: components["schemas"]["TruthClass"];
            /** Unit */
            unit: string;
            /** Value */
            value: unknown;
        };
        /**
         * AssumptionStatus
         * @enum {string}
         */
        AssumptionStatus: "DRAFT" | "APPROVED" | "EXPIRED" | "SUPERSEDED";
        /** AuditEvent */
        AuditEvent: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Type */
            actor_type: string;
            /** After Hash */
            after_hash?: string | null;
            /** Before Hash */
            before_hash?: string | null;
            /** Causation Id */
            causation_id?: string | null;
            /**
             * Correlation Id
             * Format: uuid
             */
            correlation_id: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            outcome: components["schemas"]["AuditOutcome"];
            /** Reason */
            reason?: string | null;
            /** Resource Id */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
        };
        /**
         * AuditOutcome
         * @enum {string}
         */
        AuditOutcome: "SUCCEEDED" | "FAILED" | "BLOCKED";
        /**
         * DataMode
         * @enum {string}
         */
        DataMode: "LIVE" | "CACHED" | "REPLAY" | "FIXTURE" | "USER_SUPPLIED";
        /** EvidenceRecord */
        EvidenceRecord: {
            /** Confidence */
            confidence: number;
            /** Dataset */
            dataset: string;
            /** Dataset Version */
            dataset_version: string;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** License */
            license: string;
            mode: components["schemas"]["DataMode"];
            /** Parent Evidence Ids */
            parent_evidence_ids?: string[];
            /** Raw Object Ref */
            raw_object_ref?: string | null;
            /** Raw Payload Hash */
            raw_payload_hash: string;
            /** Source Id */
            source_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Url */
            source_url?: string | null;
            /** Transformation */
            transformation: string;
            truth_class: components["schemas"]["TruthClass"];
        };
        /** FoundationContractSample */
        FoundationContractSample: {
            assumption: components["schemas"]["Assumption"];
            audit_event: components["schemas"]["AuditEvent"];
            evidence: components["schemas"]["EvidenceRecord"];
            metric: components["schemas"]["MetricEnvelope_float_"];
            source_health: components["schemas"]["SourceHealthRecord"];
        };
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "LIVE" | "RECENT" | "CURRENT" | "STALE" | "REPLAY" | "UNAVAILABLE";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Service
             * @default sanjiv-api
             * @constant
             */
            service: "sanjiv-api";
            /**
             * Status
             * @enum {string}
             */
            status: "alive" | "ready";
            /**
             * Version
             * @default 0.1.0
             * @constant
             */
            version: "0.1.0";
        };
        /** MetricEnvelope[float] */
        MetricEnvelope_float_: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Confidence */
            confidence: number;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            freshness_status: components["schemas"]["FreshnessStatus"];
            /** Model Version */
            model_version: string;
            /** Source Refs */
            source_refs: components["schemas"]["SourceRef"][];
            /** Transformation */
            transformation: string;
            truth_class: components["schemas"]["TruthClass"];
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** SourceHealthRecord */
        SourceHealthRecord: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Circuit Open
             * @default false
             */
            circuit_open: boolean;
            /** Error Code */
            error_code?: string | null;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /** Expected Cadence Seconds */
            expected_cadence_seconds?: number | null;
            freshness_status: components["schemas"]["FreshnessStatus"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Lag Seconds */
            lag_seconds?: number | null;
            /** Last Success At */
            last_success_at?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            mode: components["schemas"]["DataMode"];
            /** Source Id */
            source_id: string;
            /** Stale After Seconds */
            stale_after_seconds?: number | null;
            state: components["schemas"]["SourceState"];
        };
        /** SourceRef */
        SourceRef: {
            /** Record Id */
            record_id: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * SourceState
         * @enum {string}
         */
        SourceState: "READY" | "DEGRADED" | "UNAVAILABLE" | "RATE_LIMITED" | "DISABLED";
        /**
         * TruthClass
         * @enum {string}
         */
        TruthClass: "OBSERVED" | "DERIVED" | "INFERRED" | "MODELED" | "ASSUMPTION";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contract_sample_api_v1_contracts_sample_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationContractSample"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
